# Personal Information
[personal]
name = "Mark Matthias Reuter"
title = "Full-Stack Software Engineer | Electronic Systems Engineer"
location = "Cape Town, South Africa"
email = "mmreuter@protonmail.com"
phone = "+27 71 863 5223"
github = "github.com/x10zyn"
linkedin = "linkedin.com/in/mark-matthias-reuter-49b4b8251"
website = "github.com/x10zyn" 